from typing import List, Optional
from pydantic import BaseModel, Field


class ChatMessage(BaseModel):
    role: str = Field(..., description="Role: 'user' or 'model'")
    content: str = Field(..., description="Message text")


class DestinationCard(BaseModel):
    id: int
    name: str
    region: str
    category: str
    type: str
    price: Optional[float] = None
    rating: Optional[float] = None
    image: Optional[str] = None


class ChatRequest(BaseModel):
    message: str = Field(..., description="User message")
    history: Optional[List[ChatMessage]] = Field(default=[], description="Previous conversation turns")
    language: Optional[str] = Field(default="fr", description="Language preference")


class ChatResponse(BaseModel):
    reply: str = Field(..., description="Assistant reply generated by Gemini")
    suggestions: List[DestinationCard] = Field(default=[], description="Relevant destination cards to display")
    quick_questions: List[str] = Field(default=[], description="Suggested follow-up questions")
